package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      com.cn21.flutter.plugin.Cn21basePlugin.registerWith(shimPluginRegistry.registrarFor("com.cn21.flutter.plugin.Cn21basePlugin"));
      io.flutter.plugins.connectivity.ConnectivityPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.connectivity.ConnectivityPlugin"));
      com.idlefish.flutterboost.FlutterBoostPlugin.registerWith(shimPluginRegistry.registrarFor("com.idlefish.flutterboost.FlutterBoostPlugin"));
      io.flutter.plugins.pathprovider.PathProviderPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.pathprovider.PathProviderPlugin"));
      com.cn21.flutter.network.restfulapi.RestfulClientPlugin.registerWith(shimPluginRegistry.registrarFor("com.cn21.flutter.network.restfulapi.RestfulClientPlugin"));
      com.cn21.app.navigation.flutter.UniRouterPlugin.registerWith(shimPluginRegistry.registrarFor("com.cn21.app.navigation.flutter.UniRouterPlugin"));
  }
}
