builders:
  restfulServiceGenBuilder:
    target: ":restfulapi_generator"
    import: "package:restfulapi_generator/restfulapi_generator.dart"
    builder_factories: ["restfulServiceGenBuilder"]
    build_extensions: {".dart": [".restapi.part"]}
    build_to: source
    auto_apply: root_package